name: Create Blend

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # Runs daily at 3 AM UTC

env:
  DOTNET_VERSION: "8.0.x"
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: "true"
  TERM: "xterm"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run
        run: >-
          dotnet run --project ./src/SpotiMate/SpotiMate.csproj -c Release
          --
          create-blend
          --client-id=${{secrets.CLIENT_ID}}
          --client-secret=${{secrets.CLIENT_SECRET}}
          --refresh-token=${{secrets.REFRESH_TOKEN}}
          --blend-refresh-token=${{secrets.BLEND_REFRESH_TOKEN}}
          --blend-playlist-id=${{secrets.BLEND_PLAYLIST_ID}}
          --blend-additional-playlists=${{secrets.BLEND_ADDITIONAL_PLAYLISTS}}
          --blend-size=${{vars.BLEND_SIZE}}
