name: Synchronize Spotify

on:
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: 'true'
  TERM: 'xterm'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Run
      run: >-
        dotnet run --project ./src/SpotiMate/SpotiMate.csproj -c Release
        --
        --client-id=${{secrets.CLIENT_ID}}
        --client-secret=${{secrets.CLIENT_SECRET}}
        --refresh-token=${{secrets.REFRESH_TOKEN}}
        --favorites-playlist-id=${{secrets.FAVORITES_PLAYLIST_ID}}